KMS module done
Cloudanix/cartography pull request #1
Opened 2020-12-18 06:23 UTC by kedarghule

2020-12-21 02:45 UTC, mpurusottamc commented on cartography/intel/aws/kms.py
> +    # TODO: Gives error for following values that may contain NULL.
Remove the TODOs :)

2020-12-21 02:47 UTC, mpurusottamc requested changes
code looks good. make the minor adjustment, then i will merge it :)

2020-12-21 02:51 UTC, mpurusottamc commented
One additional change - add index info in this file as well:
cartography/data/indexes.cypher

2020-12-21 05:39 UTC, kedarghule commented on cartography/intel/aws/kms.py
> +    # TODO: Gives error for following values that may contain NULL.
Done. You may merge

2020-12-25 15:31 UTC, mpurusottamc approved these changes
Code looks good.

2020-12-25 15:31 UTC, merged