test cases and test Data modified in azure
Cloudanix/cartography pull request #168
Opened 2022-10-03 07:04 UTC by sagarnavale

2022-10-03 07:55 UTC, ganeshjagdale9545 approved these changes
Looks good

2022-10-03 11:51 UTC, ganeshjagdale9545 commented on tests/integration/cartography/intel/gcp/test_compute.py
> +    print(actual_nodes)
Remove this print statement

2022-10-03 11:55 UTC, ganeshjagdale9545 commented on tests/integration/cartography/intel/gcp/test_gke.py
> +    data = tests.data.gcp.gke.GKE_RESPONSE.get('clusters', {})
Instead of use this convert this data into list format in data file of gke

2022-10-03 11:56 UTC, ganeshjagdale9545 commented on tests/integration/cartography/intel/gcp/test_gke.py
> +    data = tests.data.gcp.gke.GKE_RESPONSE.get('clusters', {})
Change data format in data file

2022-10-03 12:00 UTC, ganeshjagdale9545 requested changes
few minor changes needed

2022-10-04 05:16 UTC, ganeshjagdale9545 approved these changes
Looks good

2022-10-04 06:35 UTC, mpurusottamc commented
Thanks for merging the code @sagarnavale and @ganeshjagdale9545 for reviewing this code.

2022-10-04 06:35 UTC, merged