Added security contact
Cloudanix/cartography pull request #169
Opened 2022-10-04 08:34 UTC by ajinkya1986

2022-10-07 04:26 UTC, ganeshjagdale9545 commented on cartography/intel/azure/securitycenter.py
> +def transform_security_contacts(security_contacts: List[Dict], subscription_id: str, common_job_parameters: str):
Return format for method is missing

2022-10-07 04:27 UTC, ganeshjagdale9545 commented on cartography/intel/azure/securitycenter.py
> +def get_security_center_client(credentials: Credentials, subscription_id: str, region: str):
Return format for method is missing

2022-10-07 04:29 UTC, ganeshjagdale9545 commented on cartography/intel/azure/securitycenter.py
> +    SET c.lastupdated = {update_tag}
region property missing

2022-10-07 04:34 UTC, ganeshjagdale9545 commented on cartography/intel/azure/securitycenter.py
> +        if common_job_parameters.get('pagination', {}).get('security_contacts', None):
`security_contacts` change to `securitycenter `

2022-10-07 04:36 UTC, ganeshjagdale9545 requested changes
minor changes needed

2022-10-10 06:31 UTC, ganeshjagdale9545 approved these changes
looks good

2022-10-10 07:45 UTC, mpurusottamc approved these changes
looks good to me.

2022-10-10 07:45 UTC, merged