Azure Storage Code Modifications and Integration tests added
Cloudanix/cartography pull request #17
Opened 2021-03-10 07:50 UTC by kedarghule

2021-03-12 03:03 UTC, mpurusottamc requested changes
left few comments. please make the adjustments

2021-03-12 03:03 UTC, mpurusottamc commented on cartography/intel/azure/storage.py
>      ON CREATE SET share.firstseen = timestamp(), share.lastupdated = {azure_update_tag}
same as above

2021-03-12 03:03 UTC, mpurusottamc commented on cartography/intel/azure/storage.py
> +                              ) -> Generator[Any, Any, Any]:
change this as line 588-591. This would fail in flake8 syntax check

2021-03-12 03:03 UTC, mpurusottamc commented on cartography/intel/azure/storage.py
>      ON CREATE SET bc.firstseen = timestamp(), bc.lastupdated = {azure_update_tag}
same as above for lastupdated and type

2021-03-12 03:03 UTC, mpurusottamc commented on cartography/intel/azure/storage.py
>      common_job_parameters['AZURE_SUBSCRIPTION_ID'] = subscription_id
this can be removed. __init__.py would add this key in common_job_parameters

2021-03-12 03:03 UTC, mpurusottamc commented
add the package dependency in setup.py file

2021-03-12 07:49 UTC, kedarghule commented
Made necessary changes

2021-03-13 06:30 UTC, mpurusottamc approved these changes
Looks good. Will merge upstream master now

2021-04-26 07:24 UTC, closed without merging