neo4j version update query in aws
Cloudanix/cartography pull request #176
Opened 2022-10-21 11:26 UTC by sagarnavale

2022-10-21 13:10 UTC, ganeshjagdale9545 commented on cartography/data/jobs/cleanup/aws_account_dns_cleanup.json
> +      "query": "MATCH (n:AWSDNSRecord)-[:MEMBER_OF_DNS_ZONE]->(:AWSDNSZone)<-[:RESOURCE]-(:AWSAccount{id: $AWS_ID})<-[:OWNER]-(:CloudanixWorkspace{id: {WORKSPACE_ID}}) WHERE n.lastupdated <> $UPDATE_
make change for `WORKSPACE_ID`

2022-10-21 13:14 UTC, ganeshjagdale9545 commented on cartography/data/jobs/cleanup/aws_import_apigateway_cleanup.json
> +      "query": "MATCH (:APIGatewayStage)<-[r:ASSOCIATED_WITH]-(:APIGatewayRestAPI)<-[:RESOURCE]-(:AWSAccount{id: $AWS_ID})<-[:OWNER]-(:CloudanixWorkspace{id: $WORKSPACE_ID}) WHERE r.lastupdated <> $U
add space between `LIMIT` and `$LIMIT_SIZE`

2022-10-21 13:35 UTC, ganeshjagdale9545 commented on cartography/intel/aws/cloudwatch.py
> +    MATCH (owner:AWSAccount{id: $AWS_ACCOUNT_ID}})
remove extra `}`

2022-10-21 13:36 UTC, ganeshjagdale9545 commented on cartography/intel/aws/cloudwatch.py
> +    SET r.lastupdated = aws_update_tag
`$` missing here

2022-10-21 13:55 UTC, ganeshjagdale9545 requested changes
few minor changes needed also make changes in `cartography/data/jobs/indexes.cypher`

2022-10-27 05:25 UTC, ganeshjagdale9545 commented on cartography/data/jobs/cleanup/aws_import_apigateway_cleanup.json
> +      "query": "MATCH (:APIGatewayStage)<-[r:ASSOCIATED_WITH]-(:APIGatewayRestAPI)<-[:RESOURCE]-(:AWSAccount{id: $AWS_ID})<-[:OWNER]-(:CloudanixWorkspace{id: $WORKSPACE_ID}) WHERE r.lastupdated <> $U
make this change

2022-10-27 05:36 UTC, ganeshjagdale9545 commented on cartography/data/jobs/cleanup/azure_database_account_cleanup.json
> +      "query": "MATCH (n:AzureCosmosDBLocation)<-[:WRITE_PERMISSIONS_FROM]-(:AzureDatabaseAccount)<-[:RESOURCE]-(:AzureSubscription{id: $AZURE_SUBSCRIPTION_ID})<-[:RESOURCE]-(:AzureTenant{id: AZURE_T
`$` missing here

2022-10-27 05:38 UTC, ganeshjagdale9545 commented on cartography/data/jobs/cleanup/azure_database_account_cleanup.json
> +      "query": "MATCH (:AzureCosmosDBLocation)<-[r:WRITE_PERMISSIONS_FROM]-(:AzureDatabaseAccount)<-[:RESOURCE]-(:AzureSubscription{id: {AZURE_SUBSCRIPTION_ID}})<-[:RESOURCE]-(:AzureTenant{id: AZURE_
`$ `missing here

2022-10-27 05:54 UTC, ganeshjagdale9545 commented on cartography/data/jobs/cleanup/azure_import_virtual_machines_scale_sets_extensions_cleanup.json
> +            "query": "MATCH (:AzureVirtualMachineScaleSetExtension)<-[r:CONTAIN]-(:AzureVirtualMachineScaleSet)<-[:RESOURCE]-(:AzureSubscription{id: $AZURE_SUBSCRIPTION_ID)<-[:RESOURCE]-(:AzureTenant
`}` missing

2022-10-27 06:22 UTC, ganeshjagdale9545 commented on cartography/data/jobs/cleanup/gcp_kms_cleanup.json
> +			"query": "MATCH (n:GCPKMSCryptoKey)<-[:RESOURCE]-(:GCPKMSKeyRing)<-[:RESOURCE]-(:GCPLocation)<-[:RESOURCE]-(:GCPProject{id: $GCP_PROJECT_ID})<-[:OWNER]-(:CloudanixWorkspace{id: $WORKSPACE_ID}) WHE
make change for `LIMIT_SIZE `

2022-10-27 06:23 UTC, ganeshjagdale9545 commented on cartography/data/jobs/cleanup/gcp_kms_cleanup.json
> +			"query": "MATCH (:GCPKMSCryptoKey)<-[r:RESOURCE]-(:GCPKMSKeyRing)<-[:RESOURCE]-(:GCPLocation)<-[:RESOURCE]-(:GCPProject{id: $GCP_PROJECT_ID})<-[:OWNER]-(:CloudanixWorkspace{id: $WORKSPACE_ID}) WHE
same as above

2022-10-27 06:24 UTC, ganeshjagdale9545 commented on cartography/data/jobs/cleanup/gcp_kms_cleanup.json
> +			"query": "MATCH (n:GCPKMSKeyRing)<-[:RESOURCE]-(:GCPLocation)<-[:RESOURCE]-(:GCPProject{id: $GCP_PROJECT_ID})<-[:OWNER]-(:CloudanixWorkspace{id: $WORKSPACE_ID}) WHERE n.lastupdated <> $UPDATE_TAG
same as above

2022-10-27 07:11 UTC, ganeshjagdale9545 requested changes
few minor changes needed

2022-10-28 11:10 UTC, ganeshjagdale9545 approved these changes
looks good

2022-10-28 11:11 UTC, ganeshjagdale9545 commented
@sagarnavale can you resolve the conflicts

2022-10-31 06:16 UTC, ganeshjagdale9545 approved these changes
looks good

2022-10-31 17:58 UTC, mpurusottamc commented
looks good.

2022-10-31 17:58 UTC, merged