Added consolelinks for aws resources
Cloudanix/cartography pull request #178
Opened 2022-10-28 12:05 UTC by ajinkya1986

2022-10-28 14:07 UTC, ganeshjagdale9545 commented on cartography/intel/aws/apigateway.py
> +        certificate.consolelink = record.consolelink,
Implement  `consolelink` before the load

2022-10-28 15:21 UTC, ganeshjagdale9545 approved these changes
Looks good

2022-10-28 15:40 UTC, mpurusottamc commented on cartography/intel/aws/apigateway.py
>          for certificate in certificates:
we should move the transformation logic to a different function. this `get_client_certificates` function should focus only on getting data. Transform function can do the enrichment of attributes like consolelink, arn, etc.

2022-10-28 15:40 UTC, mpurusottamc commented on cartography/intel/aws/apigateway.py
> +        for resource in resources:
same as above. Please move this to a transform method so that it's modular.

2022-10-28 15:40 UTC, mpurusottamc commented on cartography/intel/aws/apigateway.py
> +                console_arn = f"arn:aws:apigateway:{api_region}::certificate/{api_id}"
same as above. move to a transform method.

2022-10-28 15:40 UTC, mpurusottamc commented on cartography/intel/aws/cloudformation.py
> +            stack['arn'] = stack['StackId']
move to transform method

2022-10-28 15:42 UTC, mpurusottamc requested changes
overall code looks good. Needs minor design changes to move data enrichment code to transform methods.

2022-11-03 16:13 UTC, ganeshjagdale9545 commented on cartography/intel/aws/ec2/images.py
> +            _ids = [image["ImageId"] for image in imags]
Spelling mistakes

2022-11-03 16:17 UTC, ganeshjagdale9545 approved these changes
Looks good

2022-11-03 17:36 UTC, mpurusottamc approved these changes
looks good.

2022-11-03 17:37 UTC, merged