merge lyft to cloudanix-megre-upstream
Cloudanix/cartography pull request #181
Opened 2022-11-13 17:03 UTC by sagarnavale

2022-11-16 08:06 UTC, ajinkya1986 commented on cartography/intel/aws/apigateway.py
> -@timeit
is this function removed or still there

2022-11-16 08:07 UTC, ajinkya1986 commented on cartography/intel/aws/apigateway.py
> -    certificates = []
is this method removed or still there

2022-11-16 08:25 UTC, ajinkya1986 reviewed
Make sure the transform functions are not removed. Rest looks good. @ganeshjagdale9545  can you second review it

2022-11-16 08:49 UTC, ajinkya1986 reviewed
Please check if old code was removed from cloudanix-all while merging

2022-11-16 08:49 UTC, ajinkya1986 commented on cartography/intel/gcp/iam.py
> +            raise
These were commented in latest

2022-11-30 08:13 UTC, ganeshjagdale9545 commented on cartography/data/jobs/analysis/aws_foreign_accounts.json
> +      "query": "MATCH (foreign:AWSAccount) where NOT EXISTS(foreign.inscope) SET foreign.foreign = true",
convert this query to`CloudanixWorkspace ` specific

2022-11-30 08:13 UTC, ganeshjagdale9545 commented on cartography/data/jobs/analysis/aws_foreign_accounts.json
> +      "query": "MATCH (a:AWSAccount) where EXISTS(a.inscope) AND EXISTS(a.foreign) REMOVE a.foreign",
same as above

2022-11-30 08:14 UTC, ganeshjagdale9545 commented on cartography/data/jobs/analysis/aws_lambda_ecr.json
> +            "query":"MATCH (l:AWSLambda) \n WITH COLLECT(l) as lmbda_list \n UNWIND lmbda_list as lmbda \n MATCH (e:ECRImage) \n WHERE e.digest = 'sha256:' + lmbda.codesha256 \n MERGE (lmbda)-[r:HAS]
same as above

2022-11-30 08:17 UTC, ganeshjagdale9545 commented on cartography/data/jobs/cleanup/aws_import_inspector_cleanup.json
> +        "query": "MATCH (:AWSAccount{id: $AWS_ID})-[:RESOURCE]->(n:AWSInspectorPackage) WHERE n.lastupdated <> $UPDATE_TAG WITH n LIMIT $LIMIT_SIZE DETACH DELETE (n)",
convert all above queries  to `CloudanixWorkspace` specific

2022-11-30 08:19 UTC, ganeshjagdale9545 commented on cartography/data/jobs/cleanup/aws_import_ssm_cleanup.json
> +      "query": "MATCH (:AWSAccount{id: $AWS_ID})-[:RESOURCE]->(:EC2Instance)-[r:HAS_PATCH]->(:SSMInstancePatch) WHERE r.lastupdated <> $UPDATE_TAG WITH r LIMIT $LIMIT_SIZE DELETE (r)",
convert all above queries  to `CloudanixWorkspace` specific

2022-11-30 08:57 UTC, ganeshjagdale9545 commented on cartography/intel/aws/__init__.py
> +    )
@mpurusottamc before use this we need read up around this

2022-11-30 09:02 UTC, ganeshjagdale9545 commented on cartography/intel/aws/__init__.py
> +    if sync_successful:
to use this logic `return True` from `_sync_multiple_accounts` method

2022-11-30 09:03 UTC, ganeshjagdale9545 commented on cartography/intel/aws/__init__.py
>      run_analysis_job(
also add this in above if statement

2022-11-30 09:07 UTC, ganeshjagdale9545 commented on cartography/intel/aws/ec2/load_balancer_v2s.py
> +        logger.warning(f"Failed retrieve load balancer listeners for region - . Error - {e}")
add region

2022-11-30 09:38 UTC, ganeshjagdale9545 commented on cartography/intel/aws/ec2/snapshots.py
> +from botocore.exceptions import ClientError
Imported twice

2022-11-30 09:44 UTC, ganeshjagdale9545 commented on cartography/intel/aws/ec2/snapshots.py
> +def get_snapshots_in_use(neo4j_session: neo4j.Session, region: str, current_aws_account_id: str) -> List[str]:
this function doesn’t used anywhere

2022-11-30 09:46 UTC, ganeshjagdale9545 commented on cartography/intel/aws/ec2/snapshots.py
> +def get_snapshots(boto3_session: boto3.session.Session, region: str, in_use_snapshot_ids: List[str]) -> List[Dict]:
`in_use_snapshot_ids ` is unused parameter

2022-11-30 09:51 UTC, ganeshjagdale9545 commented on cartography/intel/aws/iam.py
> +        return parts[4]
Verify this changes with our branch most of the our cloudanix logic removed

2022-11-30 09:54 UTC, ganeshjagdale9545 commented on cartography/intel/aws/lambda_function.py
> +        SET r.lastupdated = $aws_update_tag
Merge changes cloudanix logic don’t remove it

2022-11-30 10:03 UTC, ganeshjagdale9545 commented on cartography/intel/aws/s3.py
> -    )
revert this

2022-11-30 10:05 UTC, ganeshjagdale9545 commented on cartography/intel/aws/sqs.py
> +    queue_attributes = []
Should be dict

2022-11-30 10:09 UTC, ganeshjagdale9545 commented on cartography/intel/azure/tag.py
> +    MATCH (l) where l.id = tag.resource_id
Don’t remove cloudanix logic

2022-11-30 10:11 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/compute.py
> +        _attach_instance_service_account(session, instance, gcp_update_tag)
revert this

2022-11-30 10:17 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/iam.py
> +    load_bindings(neo4j_session, bindings, project_id, gcp_update_tag)
Verify this file with our branch

2022-11-30 10:20 UTC, ganeshjagdale9545 requested changes
few changes needed

2022-12-02 13:23 UTC, ganeshjagdale9545 commented on cartography/intel/aws/resources.py
> +    # `ec2:instance` must be included before `ssm` and `ec2:images`,
ssm not included here

2022-12-02 13:44 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/iam.py
> +    logger.info(f"Time to process Compute: {toc - tic:0.4f} seconds")
Verify this file most of the cloudanix logic removed

2022-12-02 13:46 UTC, ganeshjagdale9545 requested changes
few changes needed 
also update for cloudanix aws/s3 with lyft aws/s3

2022-12-03 08:18 UTC, mpurusottamc commented on cartography/intel/aws/s3.py
> -aws_console_link = AWSLinker()
we should not delete this line. console link api calls would fail.

2022-12-03 08:19 UTC, mpurusottamc requested changes
can you fix the s3 console link issue? I will review other files in the meantime

2022-12-03 08:19 UTC, mpurusottamc commented
@sagarnavale also, resolve the conflicts

2022-12-03 23:43 UTC, mpurusottamc commented
merging to fix things on local machine and deploy code to prod.

2022-12-03 23:43 UTC, merged