Gaurav gcp spanner
Cloudanix/cartography pull request #194
Opened 2023-02-07 13:03 UTC by GauravChawda

2023-02-08 04:54 UTC, ajinkya1986 reviewed
Add tests for relationships between nodes.

2023-02-08 04:54 UTC, ajinkya1986 commented on tests/integration/cartography/intel/gcp/test_spanner.py
> +    assert actual_nodes == expected_nodes
Add tests to check relationships between different resources. Like `instance` and `database`. `backup` and `database`

2023-02-08 16:29 UTC, ganeshjagdale9545 commented on cartography/data/indexes.cypher
> +CREATE INDEX IF NOT EXISTS FOR (n:GCPSpannerInstanceDatabase) ON (n.name);
create indexes on id

2023-02-08 16:39 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/spanner.py
> +    MERGE (instance:GCPSpannerInstance{name:record.name})
load `name` as id

2023-02-08 16:44 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/spanner.py
> +        instance.name = record.name,
name field of api have format `projects/<project>/instances/[a-z][-a-z0-9]*[a-z0-9]`. we load name field as a name of instance only

2023-02-08 16:48 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/spanner.py
> +    MERGE (instance_config:GCPSpannerInstanceConfig{name: record.name})
load name as id

2023-02-08 16:49 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/spanner.py
> +        instance_config.name = record.name,
same as above

2023-02-08 17:16 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/spanner.py
> +    MERGE (replica:GCPSpannerInstanceConfigReplica{default_leader_location: record.defaultLeaderLocation, location: record.location, type: record.type})
create id for replica in the format `instance_config_id/replica_location`

2023-02-08 17:17 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/spanner.py
> +    MERGE (replica:GCPSpannerInstanceConfigReplica{default_leader_location: record.defaultLeaderLocation, location: record.location, type: record.type})
here load only `id`

2023-02-08 17:22 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/spanner.py
> +    MERGE (database:GCPSpannerInstanceDatabase{name: record.name})
load name as id

2023-02-08 17:28 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/spanner.py
> +        database.name = record.name,
name should be a display name take it from name field of api

2023-02-08 17:38 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/spanner.py
> +    MERGE (backup:GCPSpannerInstanceBackup{name: record.name})
load name as id

2023-02-08 17:39 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/spanner.py
> +        backup.name = record.name,
same as above

2023-02-08 17:41 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/spanner.py
> +    MERGE (backup)-[r:OF_DATABASE]->(database)
also create relationship between instance

2023-02-08 17:45 UTC, ganeshjagdale9545 requested changes
few minor changes

2023-02-09 16:53 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/spanner.py
> +        instance['instance_id'] = instance['name'].split('/')[-1]
`instance_id` rename to `name`

2023-02-09 16:54 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/spanner.py
> +        instance.name = record.instance_id,
`instance_id` rename to `name`

2023-02-09 16:56 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/spanner.py
> +            replica['id'] = instance_config.get('name') + '/replicas/' + replica.get('location')
Instead of this use f string

2023-02-09 16:59 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/spanner.py
> +        replica.id = record.id,
load field once

2023-02-09 16:59 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/spanner.py
> +        instance_config.id = record.id,
load field once

2023-02-09 16:59 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/spanner.py
> +        instance.region = record.region,
load field once

2023-02-09 17:00 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/spanner.py
> +        instance.id = record.id,
load field once

2023-02-09 17:06 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/spanner.py
> +        print(f"found -> {da['restoreInfo']['backupInfo']['backup']}")
Remove print statement

2023-02-09 17:07 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/spanner.py
> +        database.id = record.id,
same as above

2023-02-09 17:08 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/spanner.py
> +        backup.id = record.id,
same as above

2023-02-09 17:10 UTC, ganeshjagdale9545 requested changes
code overall looks good. few minor changes needed

2023-02-10 16:57 UTC, ganeshjagdale9545 approved these changes
looks good

2023-02-10 22:48 UTC, mpurusottamc approved these changes
looks good.

2023-02-10 22:48 UTC, mpurusottamc commented
@GauravChawda can you resolve the conflicts? I will merge your code after that.

2023-02-11 14:40 UTC, mpurusottamc commented on cartography/intel/gcp/__init__.py
> -    'Services', 'compute storage gke dns cloudfunction crm_v1 crm_v2 cloudkms cloudrun iam apigateway sql bigtable firestore apikey bigquery spanner',
did we by mistake remove spanner? I see few more areas where spanner is missing below.

2023-02-11 14:40 UTC, mpurusottamc commented on cartography/intel/gcp/__init__.py
> -    spanner='spanner.googleapis.com'
like this.

2023-02-11 14:40 UTC, mpurusottamc commented on cartography/intel/gcp/__init__.py
> -        spanner=_get_spanner_resource(credentials)
here also

2023-02-11 14:40 UTC, mpurusottamc commented on cartography/intel/gcp/__init__.py
> -def _get_spanner_resource(credentials: GoogleCredentials) -> Resource:
and here

2023-02-11 14:41 UTC, mpurusottamc commented on cartography/intel/gcp/__init__.py
> -    'Services', 'compute storage gke dns cloudfunction crm_v1 crm_v2 cloudkms cloudrun iam apigateway sql bigtable firestore apikey bigquery pubsublite',
check this properly. pubsublite is also missing here.

2023-02-11 14:41 UTC, mpurusottamc commented on cartography/intel/gcp/__init__.py
> -    pubsublite='pubsublite.googleapis.com',
spanner and pubsublite both got removed as part of merge.

2023-02-11 14:42 UTC, mpurusottamc requested changes
please check all the code again. seems we migth have gotten rid of some spanner and pubsublite related code during the merge.

2023-02-12 09:30 UTC, mpurusottamc approved these changes
looks good.

2023-02-12 09:30 UTC, merged