Added gcp pubsublite service
Cloudanix/cartography pull request #195
Opened 2023-02-09 10:39 UTC by GauravChawda

2023-02-09 17:15 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/pubsublite.py
> +    MERGE (topic:GCPPubSubLiteTopic{name: record.name})
load as `id`

2023-02-09 17:18 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/pubsublite.py
> +                subscriptions.extend(res.get('topics', []))
change for `subscriptions` here

2023-02-09 17:20 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/pubsublite.py
> +        subscription.id = record.id,
load once

2023-02-09 17:21 UTC, ganeshjagdale9545 requested changes
few minor changes needed

2023-02-10 05:07 UTC, ajinkya1986 requested changes
Changes as suggested by @ganeshjagdale9545

2023-02-10 16:59 UTC, ganeshjagdale9545 approved these changes
Looks good

2023-02-10 22:45 UTC, mpurusottamc approved these changes
looks good.

2023-02-10 22:45 UTC, merged