added gcp dataflow
Cloudanix/cartography pull request #196
Opened 2023-02-12 07:25 UTC by GauravChawda

2023-02-13 17:02 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/dataflow.py
> +        req = dataflow.projects().jobs().list(projectId=project_id)
To list the all jobs across all regions, use projects.jobs.aggregated. Using projects.jobs.list is not recommended, as you can only get the list of jobs that are running in us-central1
https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.jobs/list

2023-02-13 17:24 UTC, ganeshjagdale9545 requested changes
one minor change needed

2023-02-14 01:01 UTC, mpurusottamc approved these changes
looks good to me.

2023-02-14 01:01 UTC, mpurusottamc commented
@GauravChawda can you resolve conflicts here?

2023-02-14 16:07 UTC, ganeshjagdale9545 approved these changes
Looks good

2023-02-15 09:04 UTC, ajinkya1986 approved these changes
Looks good

2023-02-16 22:40 UTC, merged