gcp cloudtasks added
Cloudanix/cartography pull request #197
Opened 2023-02-12 13:07 UTC by GauravChawda

2023-02-13 16:48 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/cloudtasks.py
> +        if not location_id:
check for `not` here. is `not` require here?

2023-02-13 16:52 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/resources.py
> +>>>>>> > ce5d7086e0711afa1dad6457719e58fef723f78b
Remove this

2023-02-13 16:53 UTC, ganeshjagdale9545 requested changes
few minor changes needed

2023-02-14 00:59 UTC, mpurusottamc approved these changes
looks good to me.

2023-02-14 01:01 UTC, merged