Rds public exposure
Cloudanix/cartography pull request #209
Opened 2023-03-03 19:32 UTC by GauravChawda

implicit association rule is remaining because relationship regarding implicit association of route_table and subnet has to be done after both the resource are loaded.

2023-03-06 17:05 UTC, ganeshjagdale9545 commented on cartography/intel/aws/rds.py
> +            MERGE (attrib:RDSSnapshotAttribute{name: attribute.AttributeName})
Implement cleanup job for this

2023-03-06 17:06 UTC, ganeshjagdale9545 requested changes
one minor change

2023-03-09 16:36 UTC, ganeshjagdale9545 approved these changes
looks good

2023-03-13 16:21 UTC, ganeshjagdale9545 approved these changes
Looks good

2023-03-15 16:53 UTC, mpurusottamc approved these changes
looks good.

2023-03-15 16:53 UTC, merged