Elasticache cluster public exposure
Cloudanix/cartography pull request #211
Opened 2023-03-04 11:59 UTC by GauravChawda

2023-03-06 17:13 UTC, ganeshjagdale9545 commented on cartography/intel/aws/elasticache.py
> +            MERGE (:EC2SecurityGroup{id: sg.SecurityGroupId})<-[:MEMBER_OF_EC2_SECURITY_GROUP]-(cluster)
create separate function for this

2023-03-06 17:15 UTC, ganeshjagdale9545 commented on cartography/intel/aws/elasticache.py
> +    attach_elasticache_clusters_to_security_groups(neo4j_session, clusters, update_tag)
Method not declared

2023-03-06 17:15 UTC, ganeshjagdale9545 commented on cartography/intel/aws/elasticache.py
> +            MERGE (:EC2SecurityGroup{id: sg.SecurityGroupId})<-[:MEMBER_OF_EC2_SECURITY_GROUP]-(cluster)
also create cleanup job for this

2023-03-06 17:16 UTC, ganeshjagdale9545 requested changes
Minor changes needed

2023-03-09 16:40 UTC, ganeshjagdale9545 approved these changes
Looks good

2023-03-13 16:17 UTC, ganeshjagdale9545 approved these changes
Looks good

2023-03-14 19:21 UTC, mpurusottamc approved these changes
looks good.

2023-03-15 16:40 UTC, mpurusottamc approved these changes
looks good.

2023-03-15 16:40 UTC, merged