gcp sql instance analysis added and tested
Cloudanix/cartography pull request #216
Opened 2023-03-14 17:14 UTC by Aryan-code-dev

2023-03-16 16:42 UTC, ganeshjagdale9545 commented on cartography/intel/gcp/sql.py
> +                        item['authorizedNetworksList'].append(network['value'])
get `authorizedNetworks ` object like this 
`item[authorizedNetworksList]=item.get('settings', {}).get('ipConfiguration', {}).get('authorizedNetworks',[])`

2023-03-16 16:42 UTC, ganeshjagdale9545 requested changes
one minor change

2023-03-17 17:24 UTC, ganeshjagdale9545 approved these changes
looks good

2023-03-17 17:25 UTC, ganeshjagdale9545 commented
@Aryan-code-dev please resolve conflict

2023-03-17 18:21 UTC, mpurusottamc approved these changes
looks good.

2023-03-17 18:21 UTC, merged