Azure vm public facing
Cloudanix/cartography pull request #221
Opened 2023-03-17 14:52 UTC by GauravChawda

2023-03-17 17:10 UTC, ganeshjagdale9545 commented on cartography/data/jobs/analysis/azure_vm_asset_exposure.json
> +	"name": "Azure virtual machines asset internet exposure"
Implement for security groups also

2023-03-17 17:19 UTC, ganeshjagdale9545 requested changes
Implement for security groups also

2023-03-20 06:56 UTC, ganeshjagdale9545 approved these changes
Looks good

2023-03-20 07:19 UTC, mpurusottamc approved these changes
looks good.

2023-03-20 07:20 UTC, merged