added public facing tags to child resource of apigateway
Cloudanix/cartography pull request #231
Opened 2023-03-21 13:13 UTC by GauravChawda

2023-03-21 16:19 UTC, ganeshjagdale9545 commented on cartography/data/jobs/analysis/aws_apigateway_asset_exposure.json
> +			"query": "MATCH (rest_api_stage:APIGatewayStage)<-[:ASSOCIATED_WITH]-(:APIGatewayRestAPI)<-[:RESOURCE]-(:AWSAccount{id: $AWS_ID})<-[:OWNER]-(:CloudanixWorkspace{id: $WORKSPACE_ID}) WITH rest_api_s
also remove `anonymous_access` key

2023-03-21 16:23 UTC, ganeshjagdale9545 commented on cartography/data/jobs/analysis/aws_apigateway_asset_exposure.json
> +			"query": "MATCH (rest_api_stage:APIGatewayStage)<-[:ASSOCIATED_WITH]-(:APIGatewayRestAPI{anonymous_access: true})<-[:RESOURCE]-(:AWSAccount{id: $AWS_ID})<-[:OWNER]-(:CloudanixWorkspace{id: $WORKSP
set `anonymous_access` true for `APIGatewayStage`

2023-03-21 16:23 UTC, ganeshjagdale9545 commented on cartography/data/jobs/analysis/aws_apigateway_asset_exposure.json
> +			"query": "MATCH (rest_api_resource:APIGatewayResource)<-[:RESOURCE]-(:APIGatewayRestAPI{anonymous_access: true})<-[:RESOURCE]-(:AWSAccount{id: $AWS_ID})<-[:OWNER]-(:CloudanixWorkspace{id: $WORKSPA
same as above here

2023-03-21 16:24 UTC, ganeshjagdale9545 requested changes
Minor change needed

2023-03-23 04:33 UTC, ganeshjagdale9545 approved these changes
Looks good

2023-03-23 22:51 UTC, mpurusottamc commented on cartography/data/jobs/analysis/aws_apigateway_asset_exposure.json
> +			"query": "MATCH (rest_api_stage:APIGatewayStage)<-[:ASSOCIATED_WITH]-(:APIGatewayRestAPI)<-[:RESOURCE]-(:AWSAccount{id: $AWS_ID})<-[:OWNER]-(:CloudanixWorkspace{id: $WORKSPACE_ID}) WHERE EXISTS(re
public facing for stage does not make a lot of sense. because, it's more of a way to identify an environment. let's skip this object.

2023-03-23 22:51 UTC, mpurusottamc requested changes
overall code is okay. just 1 change needed

2023-03-24 23:31 UTC, merged