added public facing attributes to child resource of asg, elb
Cloudanix/cartography pull request #232
Opened 2023-03-22 06:52 UTC by GauravChawda

2023-03-23 05:08 UTC, ganeshjagdale9545 commented on cartography/data/jobs/analysis/aws_ec2_asg_asset_exposure.json
> +			"query": "MATCH (:EC2Instance{exposed_internet: true})-[:MEMBER_AUTO_SCALE_GROUP]->(asg:AutoScalingGroup)<-[:RESOURCE]-(:AWSAccount{id: $AWS_ID})<-[:OWNER]-(:CloudanixWorkspace{id: $WORKSPACE_ID})
Instead of use multiple MATCH use WHERE

2023-03-23 05:09 UTC, ganeshjagdale9545 commented on cartography/data/jobs/analysis/aws_ec2_asg_asset_exposure.json
> +			"query": "MATCH (:EC2Instance{exposed_internet: true})-[:MEMBER_AUTO_SCALE_GROUP]->(asg:AutoScalingGroup)<-[:RESOURCE]-(:AWSAccount{id: $AWS_ID})<-[:OWNER]-(:CloudanixWorkspace{id: $WORKSPACE_ID})
same as above here

2023-03-23 05:24 UTC, ganeshjagdale9545 commented on cartography/data/jobs/analysis/aws_ec2_elb_asset_exposure.json
> +			"query": "MATCH (cidr:Ipv6Range{range:'::/0'})—[:MEMBER_OF_IP_RULE]->(perm:IpPermissionInbound)—[:MEMBER_OF_EC2_SECURITY_GROUP]->(sg:EC2SecurityGroup)<-[:MEMBER_OF_EC2_SECURITY_GROUP]-(elbv2:LoadB
use MATCH path with `CloudanixWorkspace ` and `AWSAccount `

2023-03-23 05:31 UTC, ganeshjagdale9545 commented on cartography/data/jobs/analysis/aws_ec2_elb_asset_exposure.json
> +			"query": "MATCH (cidr:IpRange{range:'0.0.0.0/0'})—[:MEMBER_OF_IP_RULE]->(perm:IpPermissionInbound)—[:MEMBER_OF_EC2_SECURITY_GROUP]->(sg:EC2SecurityGroup)<-[:MEMBER_OF_EC2_SECURITY_GROUP]-(elbv2:Lo
same as above here

2023-03-23 05:33 UTC, ganeshjagdale9545 commented on cartography/data/jobs/analysis/aws_ec2_elb_asset_exposure.json
> +			"query": "MATCH (cidr:IpRange{range:'0.0.0.0/0'})—[:MEMBER_OF_IP_RULE]->(perm:IpPermissionInbound)—[:MEMBER_OF_EC2_SECURITY_GROUP]->(sg:EC2SecurityGroup)<-[:SOURCE_SECURITY_GROUP]-(elb:LoadBalance
same here

2023-03-23 05:33 UTC, ganeshjagdale9545 commented on cartography/data/jobs/analysis/aws_ec2_elb_asset_exposure.json
> +			"query": "MATCH (cidr:Ipv6Range{range:'::/0'})—[:MEMBER_OF_IP_RULE]->(perm:IpPermissionInbound)—[:MEMBER_OF_EC2_SECURITY_GROUP]->(sg:EC2SecurityGroup)<-[:SOURCE_SECURITY_GROUP]-(elb:LoadBalancer{s
same as above

2023-03-23 05:36 UTC, ganeshjagdale9545 requested changes
few minor changes needed

2023-03-25 18:23 UTC, mpurusottamc commented on cartography/data/jobs/analysis/aws_ec2_asg_asset_exposure.json
> +			"query": "MATCH (template:LaunchTemplate)<-[:HAS_LAUNCH_TEMPLATE]-(asg:AutoScalingGroup)<-[:RESOURCE]-(:AWSAccount{id: $AWS_ID})<-[:OWNER]-(:CloudanixWorkspace{id: $WORKSPACE_ID}) WHERE (:EC2Insta
public facing does not apply to launch template and launch configuration. please remove the code.

2023-03-25 18:24 UTC, mpurusottamc requested changes
minor change needed.

2023-03-27 05:28 UTC, mpurusottamc approved these changes
looks good.

2023-03-27 05:29 UTC, merged