added public facing analysis for sql instance users and datasets
Cloudanix/cartography pull request #243
Opened 2023-03-24 07:28 UTC by Aryan-code-dev

2023-03-24 07:30 UTC, ganeshjagdale9545 approved these changes
Looks good

2023-03-24 07:34 UTC, ganeshjagdale9545 requested changes
Implement cleanup query for `GCPSQLUser` and `GCPSQLDatabase`

2023-03-24 07:35 UTC, ganeshjagdale9545 commented
> Implement cleanup query for `GCPSQLUser` and `GCPSQLDatabase`

@Aryan-code-dev take look on this comment

2023-03-24 07:59 UTC, Aryan-code-dev commented
> Implement cleanup query for `GCPSQLUser` and `GCPSQLDatabase`

okay

2023-03-24 08:09 UTC, Aryan-code-dev commented
> Implement cleanup query for `GCPSQLUser` and `GCPSQLDatabase`

clean up query already exists in gcp_sql_cleanup.json

2023-03-24 23:26 UTC, mpurusottamc commented on cartography/data/jobs/analysis/gcp_sql_instance_analysis.json
> +            "query": "MATCH (u:GCPSQLUser{exposed_internet:true})<-[r:USED_BY]-(:GCPSQLInstance})<-[:RESOURCE]-(:GCPProject{id: $GCP_PROJECT_ID})<-[:OWNER]-(:CloudanixWorkspace{id: $WORKSPACE_ID}) WI
public facing logic does not apply to GCPSQLUser object. Please remove this code from this file.

2023-03-24 23:26 UTC, mpurusottamc commented on cartography/data/jobs/analysis/gcp_sql_instance_analysis.json
> +            "query": "MATCH (u:GCPSQLUser)<-[r:USED_BY]-(i:GCPSQLInstance)<-[:RESOURCE]-(:GCPProject{id: $GCP_PROJECT_ID})<-[:OWNER]-(:CloudanixWorkspace{id: $WORKSPACE_ID}) \nWHERE i.exposed_interne
same here as well.

2023-03-24 23:26 UTC, mpurusottamc requested changes
one minor change is needed.

2023-03-25 01:10 UTC, mpurusottamc approved these changes
merging it. will do the changes before deployment.

2023-03-25 01:10 UTC, merged