added public facing attributes to grandchild resource of azure storage
Cloudanix/cartography pull request #245
Opened 2023-03-27 20:20 UTC by GauravChawda

2023-03-28 03:29 UTC, ganeshjagdale9545 commented on cartography/data/jobs/analysis/azure_storage_asset_exposure.json
> +			"query": "MATCH ((n)<-[:CONTAINS]-(:AzureStorageQueueService|AzureStorageTableService|AzureStorageFileService)<-[:USES]-(:AzureStorageAccount)<-[:RESOURCE]-(:AzureSubscription{id: $AZURE_SUBSCRIPT
`(:AzureStorageQueueService|AzureStorageTableService|AzureStorageFileService)` this or statement support in 5.* version and we are using 4.* version. Implement for 4.*

2023-03-28 03:30 UTC, ganeshjagdale9545 requested changes
one minor change needed

2023-03-29 16:39 UTC, ganeshjagdale9545 approved these changes
looks good

2023-03-29 20:23 UTC, mpurusottamc approved these changes
looks good.

2023-03-29 20:23 UTC, merged