internet gateway implimention
Cloudanix/cartography pull request #254
Opened 2023-05-18 10:33 UTC by sagarnavale

2023-05-18 11:37 UTC, ganeshjagdale9545 commented on cartography/intel/azure/network.py
> +        MERGE (s:AzureNetworkSubnet{id: subnet.id})
intead of merge use match only

2023-05-18 11:38 UTC, ganeshjagdale9545 requested changes
one minor change needed

2023-05-28 17:10 UTC, mpurusottamc commented on cartography/data/jobs/cleanup/azure_import_network_nat_gateway_cleanup.json
> +            "query": "MATCH (:AzureNetworkSubnet)<-[r:ATTACHED_TO]-(:AzureNatGateway)<-[:RESOURCE]-(:AzureSubscription{id: $AZURE_SUBSCRIPTION_ID})<-[:RESOURCE]-(:AzureTenant{id: $AZURE_TENANT_ID})<-
this query should be executed first. otherwise, by the time the first 2 completes, this query would not return any data.

2023-05-28 17:13 UTC, mpurusottamc commented
Merging it, will fix it and deploy.

2023-05-28 17:13 UTC, merged