in cosmosdb add relationpship publicipaddress
Cloudanix/cartography pull request #266
Opened 2023-06-14 06:05 UTC by sagarnavale

2023-06-14 07:21 UTC, ganeshjagdale9545 reviewed
code looks good can you test before merging on your local machine

2023-06-15 05:27 UTC, mpurusottamc commented on cartography/intel/azure/cosmosdb.py
> +def _load_dadabase_account_associated_iprules(neo4j_session: neo4j.Session, database_account: Dict, azure_update_tag: int,
spelling mistake. fix this please.

2023-06-15 05:27 UTC, mpurusottamc commented on cartography/intel/azure/cosmosdb.py
> +        _load_dadabase_account_associated_iprules(neo4j_session, database_account, azure_update_tag)
spelling mistake here as well.

2023-06-15 05:28 UTC, mpurusottamc requested changes
minor fixes needed

2023-06-15 05:57 UTC, ganeshjagdale9545 approved these changes
Looks good

2023-06-15 06:40 UTC, merged