add support for github and github update cleanup and sync function
Cloudanix/cartography pull request #278
Opened 2023-10-29 18:52 UTC by sagarnavale

2023-11-14 06:04 UTC, ganeshjagdale9545 commented on cartography/data/jobs/cleanup/github_repos_cleanup.json
> +    "query": "MATCH (:CloudanixWorkspace{id: $WORKSPACE_ID})-[:OWNER]->(:GitHubOrganization)-[:REPOSITORY]->(n:GitHubRepository) WHERE n.lastupdated <> $UPDATE_TAG WITH n LIMIT $LIMIT_SIZE DETACH DEL
do cleanup jobs organization specific

2023-11-14 06:07 UTC, ganeshjagdale9545 commented on cartography/data/jobs/cleanup/github_repos_cleanup.json
> +    "query": "MATCH (:GitHubUser)-[r:OUTSIDE_COLLAB_ADMIN]->(:GitHubRepository)<-[:REPOSITORY]-(:GitHubOrganization)<-[:OWNER]-(:CloudanixWorkspace{id: $WORKSPACE_ID}) WHERE r.lastupdated <> $UPDATE_
Follow the pattern start query with `CloudanixWorkspace `

2023-11-14 06:08 UTC, ganeshjagdale9545 requested changes
minor changes needed

2023-11-26 01:14 UTC, mpurusottamc requested changes
few changes are needed. cc: @ganeshjagdale9545

2023-11-26 01:14 UTC, mpurusottamc commented on cartography/data/jobs/cleanup/github_users_cleanup.json
> +  "statements": [{
we should add cleanup for all the relationships.

2023-11-26 01:14 UTC, mpurusottamc commented on cartography/intel/github/repos.py
> +            repositories(first: 50, after: $cursor){
does 100 fail? let's keep it as close to the upstream code as possible

2023-11-26 01:14 UTC, mpurusottamc commented on cartography/intel/github/repos.py
> +                    collaborators(affiliation: OUTSIDE, first: 50) {
same as above.

2023-11-26 01:14 UTC, mpurusottamc commented on cartography/intel/github/repos.py
> +            MERGE (user)-[r: REPOSITORY]->(repo)
let's not change the relationships. this will create a problem when we sync up with upstream

2023-11-26 01:14 UTC, mpurusottamc commented on cartography/intel/github/users.py
> +    MERGE (u)<-[r:MEMBER_OF]-(org)
same as above. let's keep the relationships same as upstream. unless absolutely necessary

2023-11-27 05:10 UTC, closed without merging