Azure snapshot relations
Cloudanix/cartography pull request #292
Opened 2023-11-28 06:37 UTC by GauravChawda

2023-11-28 10:59 UTC, ganeshjagdale9545 commented on cartography/intel/azure/compute.py
> +    WITH vm, v
add this query before `MATCH (i:AzureManagedIdentity{id: ua})` statement

2023-11-28 11:13 UTC, ganeshjagdale9545 commented on cartography/intel/azure/compute.py
> +    MERGE (s)-[r:ATTACHED_TO]->(d)
create relationship like disk ->(HAS)->snapshot

2023-11-28 11:16 UTC, ganeshjagdale9545 requested changes
few minor changes needed 
also create cleanup jobs for new nodes and relationships

2023-12-15 03:45 UTC, ganeshjagdale9545 approved these changes
Looks good

2023-12-16 20:40 UTC, mpurusottamc approved these changes
looks good.

2023-12-16 20:40 UTC, merged