Mapping uniqueid with cartography
Cloudanix/cartography pull request #322
Opened 2024-08-02 11:01 UTC by 01manasrathi

2024-08-05 07:10 UTC, ganeshjagdale9545 commented on cartography/intel/bitbucket/members.py
>      MERGE (mem:BitbucketMember{id: member.user.uuid})
Instead of uuid use member.id as id here

2024-08-05 07:15 UTC, ganeshjagdale9545 commented on cartography/intel/bitbucket/members.py
> +    workspace_members = transform_members(workspace_members)
workspace parameter missing here

2024-08-05 07:19 UTC, ganeshjagdale9545 commented on cartography/intel/bitbucket/repositories.py
> +            "project": repo['project']['uuid'],
Instead of uuid pass project name

2024-08-05 07:20 UTC, ganeshjagdale9545 commented on cartography/intel/bitbucket/repositories.py
> +            "repository": repo['uuid']
pass repository name instead of uuid

2024-08-05 07:22 UTC, ganeshjagdale9545 commented on cartography/intel/bitbucket/repositories.py
> +        repo['id'] = bitbucket_linker.get_unique_id(service="bitbucket", data=data, resource_type="member")
Check `resource_type` parameter value. we should pass `repository`

2024-08-05 07:23 UTC, ganeshjagdale9545 commented on cartography/intel/bitbucket/repositories.py
>      MERGE (re:BitbucketRepository{id:repo.uuid})
Instead of uuid use repo.id as id

2024-08-05 07:24 UTC, 01manasrathi commented on cartography/intel/bitbucket/repositories.py
>      MERGE (re:BitbucketRepository{id:repo.uuid})
ok

2024-08-05 07:25 UTC, ganeshjagdale9545 commented on cartography/intel/bitbucket/workspace.py
> +            workspace: "workspace"
pass name of the `workspace` here

2024-08-05 07:27 UTC, ganeshjagdale9545 commented on cartography/intel/bitbucket/workspace.py
>      load_workspace_data(neo4j_session, workspaces, common_job_parameters)
also make change in load query according id field

2024-08-05 07:27 UTC, ganeshjagdale9545 requested changes
Minor changes needed

2024-08-05 09:50 UTC, ganeshjagdale9545 commented on cartography/intel/bitbucket/members.py
> +    MERGE (mem:BitbucketMember{id: member.user.id})
`id` is a member's object

2024-08-05 09:55 UTC, ganeshjagdale9545 requested changes
Minor changes needed 
also add clouduniqueid in `requirements.txt` file

2024-08-05 11:03 UTC, ganeshjagdale9545 commented on docs/requirements.txt
> +clouduniqueid
can you please add latest version number here?
you can get it from gihub repo latest release or from pypi.org

2024-08-05 11:04 UTC, ganeshjagdale9545 requested changes
one minor change needed

2024-08-05 11:36 UTC, ganeshjagdale9545 approved these changes
Looks good

2024-08-09 20:18 UTC, mpurusottamc approved these changes
lgtm. merging for deployment.

2024-08-09 20:18 UTC, merged