relation between ec2 , iam
Cloudanix/cartography pull request #328
Opened 2024-08-27 15:27 UTC by 01manasrathi

2024-08-27 17:49 UTC, mpurusottamc requested changes
code overall is good, but i don't see code where the role arn is mapped to the ec2 instances. we need to implement that.

2024-09-02 06:49 UTC, ganeshjagdale9545 requested changes
few changes need

2024-09-02 06:49 UTC, ganeshjagdale9545 commented on cartography/intel/aws/ec2/instances.py
> +                iam_role_arns = get_roles_from_instance_profile(boto3_session, region, instance_profile_arn)
rename variable name to iam_roles

2024-09-02 06:49 UTC, ganeshjagdale9545 commented on cartography/intel/aws/ec2/instances.py
> +    MERGE (instance:EC2Instance {id: role.InstanceId}), (roleNode:AWSRole {arn: role.IamRoles})
role object doesn’t have `InstanceId` key
Can you check API document?
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam/client/get_instance_profile.html

2024-09-02 06:49 UTC, ganeshjagdale9545 commented on cartography/intel/aws/ec2/instances.py
> +    MERGE (instance:EC2Instance {id: role.InstanceId}), (roleNode:AWSRole {arn: role.IamRoles})
also same for `IamRoles` key instead of this use Arn

2024-09-02 06:49 UTC, ganeshjagdale9545 commented on cartography/intel/aws/ec2/instances.py
> +        role_data: List[Dict[str, Any]],
When calling this function pass this parameter value

2024-09-03 03:47 UTC, ganeshjagdale9545 approved these changes
Looks good to me

2024-09-06 19:07 UTC, mpurusottamc approved these changes
lgtm

2024-09-06 19:07 UTC, merged