additional details and regional for wafv2
Cloudanix/cartography pull request #349
Opened 2024-11-22 07:30 UTC by Anarogk

### Added
- New function `get_waf_v2_web_acl_details()` to get detailed information about individual WAF ACLs
- New function `get_waf_v2_web_acls_for_scope()` to handle get ACLs for different scopes (CLOUDFRONT/REGIONAL)
- Additional WAF ACL properties in Neo4j:
  - scope
  - default_action
  - rules_count
  - capacity

2024-11-28 03:41 UTC, ganeshjagdale9545 requested changes
one minor change needed

2024-11-28 03:41 UTC, ganeshjagdale9545 commented on cartography/intel/aws/waf.py
> +        web_acl.capacity = record.capacity,
Remove `,` from this line

2024-12-03 22:25 UTC, mpurusottamc commented on cartography/intel/aws/waf.py
> +            "Name": str(acl["Name"]),
@Anarogk can you resolve this?

2024-12-04 04:34 UTC, Anarogk commented on cartography/intel/aws/waf.py
> +            "Name": str(acl["Name"]),
I was under the impression that all the properties we store in Neo4j should be strings.

2024-12-04 23:31 UTC, mpurusottamc approved these changes
lgtm

2024-12-04 23:31 UTC, merged