Cloudfront Bug: Added Logic to map Cloudfront to S3 Buckets
Cloudanix/cartography pull request #354
Opened 2024-12-02 10:37 UTC by sash-21

2024-12-02 21:10 UTC, mpurusottamc requested changes
changes needed

2024-12-02 21:10 UTC, mpurusottamc commented on cartography/intel/aws/cloudfront.py
> +        bucketId = distribution.get("Origins", {}).get("Items", []).get("Id", "")
this will throw an error. you can't do get on an array object.

2024-12-02 21:10 UTC, mpurusottamc commented on cartography/intel/aws/cloudfront.py
> +        bucketId = distribution.get("Origins", {}).get("Items", []).get("Id", "")
also, use snake case for variable names.

2024-12-02 21:10 UTC, mpurusottamc commented on cartography/intel/aws/cloudfront.py
> +    MATCH (bucket:S3Bucket {name: record.S3bucketName})
do we have an index on name field for S3Bucket? if not, we shoudl create one. This will impact performance of the insert query.

2024-12-03 06:20 UTC, sash-21 commented
@mpurusottamc Made the changes, also added support to store multiple buckets for a `Cloudfront` if there are multiple ones present.
The query now checks for all the buckets in the list and forms a relationship with them.

2024-12-03 22:27 UTC, mpurusottamc requested changes
one more change needed

2024-12-03 22:27 UTC, mpurusottamc commented on cartography/intel/aws/cloudfront.py
> +        distribution['S3bucketName'] = bucket_names
property name needs to change. we can't call `S3BucketName` for an array of items. Please fix this.

2024-12-04 04:30 UTC, mpurusottamc approved these changes
lgtm

2024-12-04 04:30 UTC, merged