Migrating azure/iam to microsoft graph api
Cloudanix/cartography pull request #357
Opened 2024-12-18 00:13 UTC by Anarogk

2024-12-24 06:05 UTC, ganeshjagdale9545 requested changes
few changes needed

2024-12-24 06:05 UTC, ganeshjagdale9545 commented on cartography/intel/azure/iam.py
> +    client = get_default_graph_client(credentials.default_graph_credentials)
pass only `credentials `

2024-12-24 06:05 UTC, ganeshjagdale9545 commented on cartography/intel/azure/iam.py
> +    client = get_default_graph_client(credentials.default_graph_credentials)
same as above

2024-12-24 06:05 UTC, ganeshjagdale9545 commented on cartography/intel/azure/iam.py
> +    client = get_default_graph_client(credentials.default_graph_credentials)
same as above

2024-12-31 14:45 UTC, mpurusottamc commented on cartography/intel/azure/iam.py
> +        users_response = client.users.get()
is this valid api? shouldn't this be `list`? `get` is always for one object not a list

2024-12-31 14:47 UTC, mpurusottamc commented on cartography/intel/azure/iam.py
> +            'objectType': 'microsoft.graph.user',
there are a few issues here. 
1. db field names should match with earlier names. 
2. all fields should use snake case and not mixed cases.

2024-12-31 14:49 UTC, mpurusottamc commented on cartography/intel/azure/iam.py
> +        i.created_date_time = group.createdDateTime,
create_date is missing. is it used anywhere? if yes, can we calculate date from the createdDateTime field?

2024-12-31 14:49 UTC, mpurusottamc commented on cartography/intel/azure/iam.py
> +        i.created_date_time = app.createdDateTime,
same here for create_date as well

2024-12-31 14:50 UTC, mpurusottamc commented on cartography/intel/azure/iam.py
> +        i.deleted_date_time = service.deletedDateTime,
there's no created realted date fields. are we not getting it in the new apis?

2024-12-31 14:50 UTC, mpurusottamc commented on cartography/intel/azure/iam.py
> +        i.authentication_type = domain.authenticationType,
here also, no created_date related fields mapping.

2024-12-31 14:51 UTC, mpurusottamc requested changes
few changes are needed

2025-06-06 08:22 UTC, ganeshjagdale9545 commented
@mpurusottamc Azure IAM not working in prod. So we could not use JIT. For testing merging this code to my branch.

2025-06-06 08:23 UTC, merged