Added documentation and tests for Azure network and minor changes in the get Azure Network usages method
Cloudanix/cartography pull request #45
Opened 2021-11-16 12:25 UTC by ganeshjagdale9545

2021-11-17 01:01 UTC, mpurusottamc commented on cartography/data/indexes.cypher
> +CREATE INDEX ON :AzureNetworkUsege(id);
Spelling mistake. It should be `AzureNetworkUsage`

2021-11-17 01:02 UTC, mpurusottamc commented on cartography/data/jobs/cleanup/azure_import_networks_usages_cleanup.json
> +            "query": "MATCH (n:AzureNetworkUsege)<-[:CONTAIN]-(:AzureNetwork)<-[:RESOURCE]-(:AzureSubscription{id: {AZURE_SUBSCRIPTION_ID}}) WHERE n.lastupdated <> {UPDATE_TAG} WITH n LIMIT {LIMIT_SI
Please change `AzureNetworkUsege` to `AzureNetworkUsage` everywhere

2021-11-17 01:02 UTC, mpurusottamc requested changes
one minor change needed

2021-11-18 05:54 UTC, mpurusottamc approved these changes
Looks good. Thanks for making the changes.

2021-12-06 09:03 UTC, ganeshjagdale9545 commented
New Branch created for Azure Networks(azure-networks)

2021-12-06 09:03 UTC, closed without merging